check for default partition before creating partitions

diff --git a/postgresql_server/templates/partitioning.sh.j2 b/postgresql_server/templates/partitioning.sh.j2
--- a/postgresql_server/templates/partitioning.sh.j2
+++ b/postgresql_server/templates/partitioning.sh.j2
@@ -22,7 +22,12 @@ create_partition() {
 
 {% for database in postgresql_partitioning_databases %}
 {% for table in database['tables'] %}
-create_partitions "{{ database.database}}" "{{ database.user }}" "{{ table }}" {{ postgresql_partitioning_days_ahead }}
+/usr/local/bin/psql -c "\d {{ table }}_default; {{ database.database }} {{ database.user }}" > /dev/null 2>&1
+if [ $? -eq 0 ];
+    create_partitions "{{ database.database}}" "{{ database.user }}" "{{ table }}" {{ postgresql_partitioning_days_ahead }}
+else
+    echo "not creating partitions for table {{ table }} because default partition {{ table }}_default was not found"
+fi
 {% endfor %}
 {% endfor %}
 
