more work on partitioning script

diff --git a/postgresql_server/templates/partitioning.sh.j2 b/postgresql_server/templates/partitioning.sh.j2
--- a/postgresql_server/templates/partitioning.sh.j2
+++ b/postgresql_server/templates/partitioning.sh.j2
@@ -1,27 +1,42 @@
 #!/bin/sh
 
 create_partitions() {
-    database=$1
-    user=$2
-    parent=$3
-    days=$4
-    /usr/local/bin/psql -c "\d ${parent}_default;" ${database} ${user} > /dev/null 2>&1
-    if [ "$?" -eq "0" ]; then
-        echo "--- Creating $days partitions for database $database user $user parent table $parent"
-        for day in $(seq 1 ${days}); do
-            create_partition $database $user $parent ${parent}_$(date -v"+${day}d" +%Y_%m_%d)
-        done
-    else
-        echo "not creating partitions for table ${parent} because default partition ${parent}_default was not found"
+    DATABASE=$1
+    USER=$2
+    PARENT=$3
+    DAYS=$4
+
+    # check if we have a default partition for this table
+    /usr/local/bin/psql -c "\d ${PARENT}_default;" ${DATABASE} ${USER} > /dev/null 2>&1
+    if [ "$?" -ne "0" ]; then
+        echo "not creating partitions for table ${PARENT} because default partition ${PARENT}_default was not found"
+        return
+    fi
+
+    echo "--- Creating $DAYS partitions for database $DATABASE user $USER parent table $PARENT"
+    for DAY in $(seq 1 ${DAYS}); do
+        PARTITION="${PARENT}_$(date -v"+${DAY}d" +%Y_%m_%d)"
+        START=$(date -v"+${DAY}d" +%Y-%m-%d)
+        END=$(date -v"+$(echo ${DAY}+1|bc)d" +%Y-%m-%d)
+        create_partition "${DATABASE}" "${USER}" "${PARENT}" "${PARTITION}" "${START}" "${END}"
+    done
 }
 
 create_partition() {
-    database=$1
-    user=$2
-    parent=$3
-    partition=$4
-    echo "--- Creating table $partition like table $parent in database $database with user $user"
-    /usr/local/bin/psql -c "create table if not exists ${partition} (like ${parent} including all);" ${database} ${user}
+    DATABASE=$1
+    USER=$2
+    PARENT=$3
+    PARTITION=$4
+    START=$5
+    END=$6
+
+    # create the partition
+    echo "--- Creating table $PARTITION like table $PARENT in database $DATABASE with user $USER"
+    /usr/local/bin/psql -c "CREATE TABLE IF NOT EXISTS ${PARTITION} (LIKE ${PARENT} INCLUDING ALL);" ${DATABASE} ${USER}
+
+    # attach the partition
+    echo "--- Attaching partition $PARTITION to parent table table $PARENT for values from ${START} to ${END}"
+    /usr/local/bin/psql -c "ALTER TABLE ${PARENT} ATTACH PARTITION ${PARTITION} FOR VALUES FROM ( '${START}' ) TO ( '${END}' );"
 }
 
 {% for database in postgresql_partitioning_databases %}
